# Generated by Django 4.2.16 on 2024-11-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='author_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ornament',
            name='letter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.letter'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
