# Generated by Django 4.2.16 on 2024-11-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_letter_author_name_alter_ornament_letter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ornament',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tree',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
