# Generated by Django 4.2.16 on 2024-11-21 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_letter_options_alter_ornament_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ornaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('letter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.letters')),
            ],
        ),
        migrations.CreateModel(
            name='Trees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ornament',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='ornament',
            name='tree',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letter',
        ),
        migrations.DeleteModel(
            name='Ornament',
        ),
        migrations.DeleteModel(
            name='Tree',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='trees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.users'),
        ),
        migrations.AddField(
            model_name='ornaments',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trees'),
        ),
        migrations.AddField(
            model_name='letters',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.trees'),
        ),
    ]
