# Generated by Django 4.2.16 on 2024-11-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('letter_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.user')),
            ],
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('ornament_id', models.AutoField(primary_key=True, serialize=False)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.letter')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.tree')),
            ],
        ),
        migrations.AddField(
            model_name='letter',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tree.tree'),
        ),
    ]
