# Generated by Django 4.2.16 on 2024-11-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_alter_letter_author_name_alter_tree_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='author_name',
            field=models.CharField(max_length=50),
        ),
    ]
